SELECT CRCC.CAR_ID, CRCC.CAR_TYPE, ROUND(CRCC.DAILY_FEE * 30 * (100-CRCD.DISCOUNT_RATE) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR CRCC JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CCRH ON CRCC.CAR_ID = CCRH.CAR_ID JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CRCD ON CRCC.CAR_TYPE = CRCD.CAR_TYPE
WHERE CRCD.DURATION_TYPE LIKE '30%'
AND CRCC.CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01')
GROUP BY CRCC.CAR_ID
HAVING CRCC.CAR_TYPE IN ('세단', 'SUV') AND FEE BETWEEN 500000 AND 2000000 
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;