SELECT RO.FOOD_TYPE, RO.REST_ID, RO.REST_NAME, RO.FAVORITES
FROM REST_INFO RO
WHERE RO.FAVORITES = (SELECT MAX(RI.FAVORITES) FROM REST_INFO RI WHERE RI.FOOD_TYPE = RO.FOOD_TYPE)
GROUP BY FOOD_TYPE
ORDER BY RO.FOOD_TYPE DESC;