WITH RECURSIVE GENE AS(
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION
    SELECT E.ID, E.PARENT_ID, G.GENERATION+1 AS GENERATION
    FROM ECOLI_DATA E JOIN GENE G ON E.PARENT_ID = G.ID
)
SELECT COUNT(*) AS COUNT, GENERATION
FROM GENE
WHERE ID NOT IN (SELECT DISTINCT PARENT_ID FROM GENE WHERE PARENT_ID IS NOT NULL)
GROUP BY GENERATION
ORDER BY GENERATION;