WITH RECURSIVE TIME AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM TIME
    WHERE HOUR < 23
)
SELECT T.HOUR, IFNULL(A.COUNT, 0) AS COUNT # 개수
FROM TIME T LEFT JOIN (
    SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR(DATETIME)
) A
ON T.HOUR = A.HOUR # 같은 시간대
ORDER BY T.HOUR;