WITH TBL AS (
SELECT SUM(CASE WHEN GRADE.HALF_YEAR = 1 THEN GRADE.SCORE ELSE 0 END)
        + SUM(CASE WHEN GRADE.HALF_YEAR = 2 THEN GRADE.SCORE ELSE 0 END) AS SCORE, EMP.EMP_NO, EMP.EMP_NAME, EMP.POSITION, EMP.EMAIL
FROM HR_DEPARTMENT DEPT JOIN HR_EMPLOYEES EMP ON DEPT.DEPT_ID = EMP.DEPT_ID
JOIN HR_GRADE GRADE ON EMP.EMP_NO =  GRADE.EMP_NO
WHERE GRADE.YEAR = '2022'
GROUP BY EMP.EMP_NO, EMP.EMP_NAME, EMP.POSITION, EMP.EMAIL)
SELECT * FROM TBL WHERE SCORE = (SELECT MAX(SCORE) FROM TBL);